set_property IOSTANDARD LVCMOS18 [get_ports ACL_CSN]
set_property IOSTANDARD LVCMOS18 [get_ports ACL_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports ACL_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports CLK100MHZ]
set_property IOSTANDARD LVCMOS18 [get_ports ACL_SCLK]
set_property PACKAGE_PIN H17 [get_ports {LED[0]}]
set_property PACKAGE_PIN K15 [get_ports {LED[1]}]
set_property PACKAGE_PIN J13 [get_ports {LED[2]}]
set_property PACKAGE_PIN N14 [get_ports {LED[3]}]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property PACKAGE_PIN E3 [get_ports CLK100MHZ]
set_property PACKAGE_PIN E15 [get_ports ACL_MISO]
set_property PACKAGE_PIN F14 [get_ports ACL_MOSI]
set_property PACKAGE_PIN D15 [get_ports ACL_CSN]
set_property PACKAGE_PIN F15 [get_ports ACL_SCLK]

set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN J15 [get_ports reset]

set_property IOSTANDARD LVCMOS18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports z]
set_property PACKAGE_PIN V15 [get_ports {LED[4]}]

set_property PACKAGE_PIN V11 [get_ports {LED[7]}]
set_property PACKAGE_PIN U16 [get_ports z]
set_property PACKAGE_PIN V12 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {AZ[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AZ[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG[6]}]
set_property PACKAGE_PIN P15 [get_ports {SEG[2]}]
set_property PACKAGE_PIN K13 [get_ports {SEG[3]}]
set_property PACKAGE_PIN T10 [get_ports {SEG[6]}]
set_property PACKAGE_PIN J17 [get_ports {AZ[0]}]
set_property PACKAGE_PIN J18 [get_ports {AZ[1]}]
set_property PACKAGE_PIN T9 [get_ports {AZ[2]}]
set_property PACKAGE_PIN U13 [get_ports {AZ[7]}]
set_property PACKAGE_PIN K2 [get_ports {AZ[6]}]
set_property PACKAGE_PIN T14 [get_ports {AZ[5]}]
set_property PACKAGE_PIN P14 [get_ports {AZ[4]}]
set_property PACKAGE_PIN J14 [get_ports {AZ[3]}]

set_property PACKAGE_PIN L18 [get_ports {SEG[0]}]
set_property PACKAGE_PIN T11 [get_ports {SEG[1]}]
set_property PACKAGE_PIN K16 [get_ports {SEG[4]}]
set_property PACKAGE_PIN R10 [get_ports {SEG[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports y]
set_property PACKAGE_PIN U16 [get_ports y]
